# Generated by Django 3.0.6 on 2020-06-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_Game_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poketype',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
