# Generated by Django 3.0.6 on 2020-06-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_Game_App', '0002_poketype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokeXp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokexp',
            field=models.ManyToManyField(to='Card_Game_App.PokeXp'),
        ),
    ]
