# Generated by Django 3.0.6 on 2020-06-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_Game_App', '0003_auto_20200606_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pokexp',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokexp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PokeXp',
        ),
    ]
